font_family      JetBrainsMono Nerd Font Mono
font_size        11.0
disable_ligatures never
shell /usr/bin/zsh

cursor_shape     block
scrollback_lines 10000
window_padding_width 8

copy_on_select   clipboard


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
